"""
System Prompts Package for Multi-Agent System.
"""

from meal_planner.prompts.system_prompts import (
    PROFILE_ANALYZER_SYSTEM_PROMPT,
    NUTRITIONIST_SYSTEM_PROMPT,
    CHEF_PLANNER_SYSTEM_PROMPT,
    DIETARY_AUDITOR_SYSTEM_PROMPT,
    GROCERY_PREP_SYSTEM_PROMPT
)

__all__ = [
    "PROFILE_ANALYZER_SYSTEM_PROMPT",
    "NUTRITIONIST_SYSTEM_PROMPT",
    "CHEF_PLANNER_SYSTEM_PROMPT",
    "DIETARY_AUDITOR_SYSTEM_PROMPT",
    "GROCERY_PREP_SYSTEM_PROMPT"
]
